services:
  web:
    build: ./
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./public:/var/www/html
    ports:
      - 8089:80
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weight_admin
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./batch/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./batch/sql/create_users.sql:/docker-entrypoint-initdb.d/create_users.sql:ro
      - ./batch/sql/create_muscle_groups.sql:/docker-entrypoint-initdb.d/create_muscle_groups.sql:ro
      - ./batch/sql/create_exercises.sql:/docker-entrypoint-initdb.d/create_exercises.sql:ro
      - ./batch/sql/create_daily_weights.sql:/docker-entrypoint-initdb.d/create_daily_weights.sql:ro
      - ./batch/sql/create_daily_calories.sql:/docker-entrypoint-initdb.d/create_daily_calories.sql:ro
    # シェルスクリプトを実行後、通常のmysqldを起動する
    command: ["/bin/bash", "/docker-entrypoint-initdb.d/init.sh", "mysqld"]

volumes:
  mysql_data: