version: "3.9"
services:
  web:
    build: ./
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./public:/var/www/html
    ports:
      - 8089:80